import type { Subtest } from "../core/types.ts";

/**
 * Gq - quantitative reasoning.
 *
 * Two subtests. numberSeries keys were generated by executing a rule
 * function and then machine-checked to confirm no constant-difference or
 * constant-ratio rule also fits the shown terms - an ambiguity that would
 * let a test-taker be scored correct for the wrong reason.
 *
 * quantComparison keys were verified by evaluating both quantities in code,
 * using exact rational and BigInt arithmetic where floats would be unsafe.
 * That check caught a fraction item keyed "B greater" that was in fact equal.
 *
 * Parameters are AUTHORED ESTIMATES, not calibrated on a sample.
 */

export const numberSeries: Subtest = {
  id: "numberSeries",
  name: "Number Series",
  broad: "Gq",
  narrow: ["RQ"],
  instructions:
    "Each row of numbers follows a rule. Work out the rule and choose the number that comes next.",
  budgetMin: 16,
  routing: { maxItems: 14, minItems: 6, ceilingMisses: 4, targetSe: 0.28, entryTheta: 0 },
  items: [
    {
      id: "nsr-001", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1, b: -2.5, c: 0.2,
      // rule: +3
      prompt: "2, 5, 8, 11, 14, ?",
      options: ["18", "16", "28", "20", "17"],
      answer: 4,
    },
    {
      id: "nsr-002", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1, b: -2.1, c: 0.2,
      // rule: +7
      prompt: "5, 12, 19, 26, 33, ?",
      options: ["66", "47", "40", "41", "39"],
      answer: 2,
    },
    {
      id: "nsr-003", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.1, b: -1.7, c: 0.2,
      // rule: x2
      prompt: "3, 6, 12, 24, 48, ?",
      options: ["96", "72", "97", "95", "120"],
      answer: 0,
    },
    {
      id: "nsr-004", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.2, b: -1.3, c: 0.2,
      // rule: squares
      prompt: "1, 4, 9, 16, 25, ?",
      options: ["37", "35", "50", "36", "34"],
      answer: 3,
    },
    {
      id: "nsr-005", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.2, b: -0.9, c: 0.2,
      // rule: pronic n(n+1)
      prompt: "2, 6, 12, 20, 30, ?",
      options: ["60", "42", "40", "43", "41"],
      answer: 1,
    },
    {
      id: "nsr-006", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.3, b: -0.5, c: 0.2,
      // rule: x3+2
      prompt: "2, 8, 26, 80, 242, ?",
      options: ["404", "729", "727", "484", "728"],
      answer: 4,
    },
    {
      id: "nsr-007", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.3, b: -0.1, c: 0.2,
      // rule: triangular
      prompt: "1, 3, 6, 10, 15, 21, ?",
      options: ["42", "34", "28", "27", "29"],
      answer: 2,
    },
    {
      id: "nsr-008", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.4, b: 0.3, c: 0.2,
      // rule: n^2+1
      prompt: "1, 2, 5, 10, 17, ?",
      options: ["26", "24", "27", "25", "34"],
      answer: 0,
    },
    {
      id: "nsr-009", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.4, b: 0.7, c: 0.2,
      // rule: cubes
      prompt: "1, 8, 27, 64, 125, ?",
      options: ["217", "215", "250", "216", "186"],
      answer: 3,
    },
    {
      id: "nsr-010", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.5, b: 1.1, c: 0.2,
      // rule: 2^n-1
      prompt: "1, 3, 7, 15, 31, ?",
      options: ["79", "63", "47", "64", "62"],
      answer: 1,
    },
    {
      id: "nsr-011", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.5, b: 1.5, c: 0.2,
      // rule: interleaved: odd positions +4, even positions x2
      prompt: "3, 2, 7, 4, 11, 8, ?",
      options: ["5", "16", "14", "12", "15"],
      answer: 4,
    },
    {
      id: "nsr-012", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.6, b: 1.9, c: 0.2,
      // rule: n^2+n+1
      prompt: "3, 7, 13, 21, 31, ?",
      options: ["42", "62", "43", "41", "44"],
      answer: 2,
    },
    {
      id: "nsr-013", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.7, b: 2.4, c: 0.2,
      // rule: x3-2
      prompt: "2, 4, 10, 28, 82, ?",
      options: ["244", "136", "245", "243", "164"],
      answer: 0,
    },
    {
      id: "nsr-014", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.8, b: 2.9, c: 0.2,
      // rule: second differences 1,2,3,4
      prompt: "1, 3, 6, 11, 19, 31, ?",
      options: ["49", "47", "62", "48", "43"],
      answer: 3,
    },
    {
      id: "nsr-015", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.9, b: 3.4, c: 0.2,
      // rule: a(n)=2a(n-1)+(n-1), with a(1)=1
      prompt: "1, 3, 8, 19, 42, ?",
      options: ["84", "89", "65", "90", "88"],
      answer: 1,
    },
    {
      id: "nsr-016", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 2, b: 3.8, c: 0.2,
      // rule: a(n)=a(n-1)+2a(n-2)
      prompt: "2, 3, 7, 13, 27, 53, ?",
      options: ["79", "108", "106", "133", "107"],
      answer: 4,
    },
  ],
};

const QC_OPTIONS = [
  "Quantity A is greater",
  "Quantity B is greater",
  "The two quantities are equal",
  "Cannot be determined from the information given",
];

export const quantComparison: Subtest = {
  id: "quantComparison",
  name: "Quantitative Comparison",
  broad: "Gq",
  narrow: ["RQ"],
  instructions:
    "Compare the two quantities. Choose whether A is greater, B is greater, they are equal, or there is not enough information to decide.",
  budgetMin: 19,
  routing: { maxItems: 15, minItems: 7, ceilingMisses: 4, targetSe: 0.28, entryTheta: 0 },
  items: [
    {
      id: "qcp-001", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1, b: -2.4, c: 0.25,
      // verified: 27 vs 26
      prompt: "Quantity A: 12 + 15\nQuantity B: 30 - 4",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-002", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1, b: -2, c: 0.25,
      // verified: 36 vs 36
      prompt: "Quantity A: 4 x 9\nQuantity B: 6 x 6",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-003", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.1, b: -1.6, c: 0.25,
      // verified: 0.5 vs 0.6
      prompt: "Quantity A: 1/2\nQuantity B: 3/5",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-004", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.2, b: -1.2, c: 0.25,
      // verified: 32 vs 25
      prompt: "Quantity A: 2^5\nQuantity B: 5^2",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-005", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.2, b: -0.8, c: 0.25,
      // verified: 20 vs 20
      prompt: "Quantity A: 25% of 80\nQuantity B: 80% of 25",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-006", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.3, b: -0.4, c: 0.25,
      // verified: 243 vs 125
      prompt: "Quantity A: 3^5\nQuantity B: 5^3",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-007", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.3, b: 0, c: 0.25,
      // verified: 30/3 = 10 vs 10
      prompt: "Quantity A: The average of 4, 8, and 18\nQuantity B: 10",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-008", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.4, b: 0.4, c: 0.25,
      // verified: 9 vs 9
      prompt: "Quantity A: x squared, where x = -3\nQuantity B: 9",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-009", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.5, b: 0.8, c: 0.25,
      // verified: x unconstrained: x=2 makes B greater, x=1/2 makes A greater
      prompt: "Quantity A: x squared\nQuantity B: x cubed",
      options: QC_OPTIONS,
      answer: 3,
    },
    {
      id: "qcp-010", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.5, b: 1.1, c: 0.25,
      // verified: 24 vs 26
      prompt: "Quantity A: The perimeter of a square with area 36\nQuantity B: The perimeter of a 4 by 9 rectangle",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-011", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.6, b: 1.4, c: 0.25,
      // verified: 1073741824 vs 3486784401
      prompt: "Quantity A: 2^30\nQuantity B: 3^20",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-012", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.6, b: 1.7, c: 0.25,
      // verified: n = 6 vs 6
      prompt: "Quantity A: n, where 3n + 7 = 25\nQuantity B: 6",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-013", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.7, b: 2, c: 0.25,
      // verified: y = 4 or y = -4
      prompt: "Quantity A: y, where y squared = 16\nQuantity B: 4",
      options: QC_OPTIONS,
      answer: 3,
    },
    {
      id: "qcp-014", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.7, b: 2.3, c: 0.25,
      // verified: 23, 29, 31, 37 = 4 vs 4
      prompt: "Quantity A: The number of primes between 20 and 40\nQuantity B: 4",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-015", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.8, b: 2.6, c: 0.25,
      // verified: 27/1000 vs 36/1000
      prompt: "Quantity A: 0.3 cubed\nQuantity B: 0.3 squared x 0.4",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-016", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.9, b: 3, c: 0.25,
      // verified: 41/42 vs 1, verified with exact rational arithmetic
      prompt: "Quantity A: 1/2 + 1/3 + 1/7\nQuantity B: 1",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-017", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.9, b: 3.3, c: 0.25,
      // verified: 823543 vs 5040
      prompt: "Quantity A: 7^7\nQuantity B: 7 factorial",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-018", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 2, b: 3.7, c: 0.25,
      // verified: 5x4x3 = 60 vs 60
      prompt: "Quantity A: The number of distinct three-letter arrangements using letters from ABCDE with no repeats\nQuantity B: 60",
      options: QC_OPTIONS,
      answer: 2,
    },
  ],
};
