import type { Subtest } from "../core/types.ts";

/**
 * Gq - quantitative reasoning.
 *
 * Two subtests. numberSeries keys were generated by executing a rule
 * function and then machine-checked to confirm no constant-difference or
 * constant-ratio rule also fits the shown terms - an ambiguity that would
 * let a test-taker be scored correct for the wrong reason.
 *
 * quantComparison keys were verified by evaluating both quantities in code,
 * using exact rational and BigInt arithmetic where floats would be unsafe.
 * That check caught a fraction item keyed "B greater" that was in fact equal.
 *
 * 2026-08 re-anchor per the 17-agent difficulty audit
 * (docs/DIFFICULTY_AUDIT.md, sections 2.4 and 2.5): the uniform b ladders
 * and lockstep a ramps were replaced with content-anchored values, nsr-012
 * and nsr-013 were rebuilt as structurally new items, and qcp-006 was moved
 * off qcp-004's twin structure. Parameters remain AUTHORED ESTIMATES, not
 * calibrated on a sample. Keys, distractor separation, anti-duplicate and
 * twin regressions live in test/gq-keys.test.ts.
 */

// ---------------------------------------------------------------------------
// Number Series (nsr-001..018)
//
// b span -3.5 .. +2.4, a 0.9-1.4 (low-b items 0.9-1.1, high-b 1.2-1.4),
// c = 1/5 (5 options). Re-anchored 2026-08 per docs/DIFFICULTY_AUDIT.md
// §2.4: the former uniform 0.4-step ladder over-priced canonical-format
// items (squares, cubes, Mersenne, x2), and the 1.0 -> 2.0 a-ramp was
// unjustified. nsr-012 previously duplicated nsr-005's difference chain
// (4,6,8,10) and nsr-013 (x3-2) was near-isomorphic to nsr-006 (x3+2) -
// both replaced. 2026-08-21 floor revision (audit §9): nsr-017/018 are
// single-step basals so chance-level performance can be located below the
// old -2.8 floor. Distractor policy: every distractor is a rule-error
// outcome (wrong operation/multiplier, one step early or late, repeat
// term, repeated or stale difference, reversed direction) and every
// distractor sits more than 3 from the key, so a near-neighbor guess gains
// nothing over the 1/5 chance level. Error types vary across items (only
// some retain the repeat-last-difference distractor) and key positions do
// not cycle. 2026-08-21 rank revision (red-team audit): the distractor
// VALUE sets were re-authored (keys, rules, prompts, display positions and
// b values all unchanged) so the key's rank among the value-sorted options
// spans all five ranks - 4 smallest / 4 second / 3 middle / 3 fourth /
// 4 largest of 18 - breaking the former second-smallest mode (8/18) and
// the never-an-extreme pattern that made "eliminate min and max"
// risk-free. The practice items were de-primed to match (their keys are
// now the smallest / the largest option). Guarded by the rank-distribution
// regression in test/gq-keys.test.ts.
// ---------------------------------------------------------------------------

export const numberSeries: Subtest = {
  id: "numberSeries",
  name: "Number Series",
  broad: "Gq",
  narrow: ["RQ"],
  instructions:
    "Each row of numbers follows a rule. Work out the rule and choose the number that comes next.",
  budgetMin: 16,
  routing: { maxItems: 14, minItems: 6, ceilingMisses: 4, targetSe: 0.50, entryTheta: 0 },
  // Unscored sample: counting by twos — the format's floor case.
  practice: [
    {
      id: "prac-nsr-01", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -3.5, c: 0.2,
      // rule: constant difference +2; key is the smallest option (the
      // practice section must not prime the second-smallest heuristic)
      prompt: "2, 4, 6, 8, ?",
      options: ["10", "16", "20", "14", "18"],
      answer: 0,
    },
    {
      id: "prac-nsr-02", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -3.5, c: 0.2,
      // rule: constant difference +10; key is the largest option (rank
      // de-priming, see prac-nsr-01)
      prompt: "5, 15, 25, 35, ?",
      options: ["40", "35", "45", "30", "25"],
      answer: 2,
    },
  ],
  items: [
    {
      id: "nsr-017", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -3.2, c: 0.2,
      // rule: constant difference +2 (basal)
      // distractors: 15 = 9+6 (doubled the step); 7 = repeated an early
      //   term; 22 = 11x2 (doubled the key); 18 = 9x2 (doubled the last
      //   term)
      prompt: "1, 3, 5, 7, 9, ?",
      options: ["15", "11", "7", "22", "18"],
      answer: 1,
    },
    {
      id: "nsr-018", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -3.5, c: 0.2,
      // rule: constant difference +1, i.e. counting (basal)
      // distractors: 14 = 7x2 (doubled the last term); 12 = 7+5 (added the
      //   previous term); 4 = repeated an early term; 15 = 7+8 (added the
      //   last two terms)
      prompt: "3, 4, 5, 6, 7, ?",
      options: ["14", "8", "12", "4", "15"],
      answer: 1,
    },
    {
      id: "nsr-001", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -2.8, c: 0.2,
      // rule: constant difference +3
      // distractors: 21 = 14+7 (doubled the step); 11 = 14-3 (reversed);
      //   28 = 14x2 (doubled the last term); 23 = 14+9 (misread step as 3x3)
      prompt: "2, 5, 8, 11, 14, ?",
      options: ["21", "17", "11", "28", "23"],
      answer: 1,
    },
    {
      id: "nsr-002", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1, b: -2.4, c: 0.2,
      // rule: constant difference +7
      // distractors: 47 = 33+14 (doubled the step); 66 = 33x2 (doubled the
      //   last term); 26 = 33-7 (reversed); 52 = 33+19 (added the previous term)
      prompt: "5, 12, 19, 26, 33, ?",
      options: ["47", "66", "26", "40", "52"],
      answer: 3,
    },
    {
      id: "nsr-003", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1, b: -2.2, c: 0.2,
      // rule: constant ratio x2
      // distractors: 72 = 48+24 (added the previous difference);
      //   144 = 48x3 (wrong multiplier); 192 = 48x2x2 (one step late);
      //   60 = 48+12 (difference from three steps back)
      prompt: "3, 6, 12, 24, 48, ?",
      options: ["96", "72", "144", "192", "60"],
      answer: 0,
    },
    {
      id: "nsr-004", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.1, b: -1.8, c: 0.2,
      // rule: squares (n^2)
      // distractors: 30 = 25+5 (added the position); 49 = 7^2 (skipped a
      //   square, one step late); 25 = repeated the last term; 50 = 25x2
      prompt: "1, 4, 9, 16, 25, ?",
      options: ["30", "49", "25", "50", "36"],
      answer: 4,
    },
    {
      id: "nsr-005", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1, b: -1.4, c: 0.2,
      // rule: pronic n(n+1); differences 4,6,8,10,12
      // distractors: 26 = 30-4 (reversed); 36 = 30+6 (reused an old
      //   difference); 38 = 30+8 (repeated the middle difference);
      //   56 = 42+14 (one step late)
      prompt: "2, 6, 12, 20, 30, ?",
      options: ["38", "56", "42", "26", "36"],
      answer: 2,
    },
    {
      id: "nsr-006", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.1, b: -0.3, c: 0.2,
      // rule: x3+2
      // distractors: 242 = repeated the last term; 322 = 242+80 (additive
      //   read); 486 = 242x2+2 (wrong multiplier); 724 = 242x3-2 (sign
      //   error on the constant)
      prompt: "2, 8, 26, 80, 242, ?",
      options: ["724", "728", "486", "322", "242"],
      answer: 1,
    },
    {
      id: "nsr-007", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1, b: -1, c: 0.2,
      // rule: triangular n(n+1)/2; differences 2,3,4,5,6,7
      // distractors: 14 = 21-7 (reversed); 15 = repeated the term before
      //   last; 21 = one step early (repeated the last term); 22 = 21+1
      //   (expected consecutive integers)
      prompt: "1, 3, 6, 10, 15, 21, ?",
      options: ["21", "22", "15", "14", "28"],
      answer: 4,
    },
    {
      id: "nsr-008", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.1, b: -0.5, c: 0.2,
      // rule: n^2+1 for n = 0, 1, 2, ...
      // distractors: 10 = repeated the term before last; 17 = repeated the
      //   last term; 22 = 17+5 (reused an old difference); 37 = 6^2+1 (one
      //   step late)
      prompt: "1, 2, 5, 10, 17, ?",
      options: ["37", "22", "26", "10", "17"],
      answer: 2,
    },
    {
      id: "nsr-009", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.1, b: -0.2, c: 0.2,
      // rule: cubes (n^3)
      // distractors: 250 = 125x2 (doubled the last term); 343 = 7^3 (one
      //   step late); 432 = 216x2 (doubled the key); 625 = 5^4 (kept the
      //   base, raised the exponent)
      prompt: "1, 8, 27, 64, 125, ?",
      options: ["216", "250", "432", "343", "625"],
      answer: 0,
    },
    {
      id: "nsr-010", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.1, b: 0.1, c: 0.2,
      // rule: 2^n - 1
      // distractors: 93 = 31x3 (wrong multiplier); 94 = 47x2 (doubled the
      //   term before last); 126 = 63x2 (doubled the key); 127 = 2^7-1
      //   (one step late)
      prompt: "1, 3, 7, 15, 31, ?",
      options: ["127", "93", "126", "63", "94"],
      answer: 3,
    },
    {
      id: "nsr-011", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.2, b: 0.8, c: 0.2,
      // rule: interleaved: odd positions +4, even positions x2
      // distractors: 7 = repeated the previous odd-chain term; 8 = repeated
      //   the last even-chain term; 9 = 8+1 (continued the even chain);
      //   11 = one step early on the odd chain (repeated the last term)
      prompt: "3, 2, 7, 4, 11, 8, ?",
      options: ["11", "9", "15", "8", "7"],
      answer: 2,
    },
    {
      id: "nsr-012", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.3, b: 1.2, c: 0.2,
      // rule: differences double (1, 2, 4, 8, 16, 32)
      // rebuilt 2026-08: the previous item (n^2+n+1) had the same difference
      // chain 4,6,8,10 as nsr-005 - the same item priced 2.8 logits apart
      // distractors: 98 = 34+64 (doubled the next difference twice);
      //   102 = 34x3 (wrong multiplier); 130 = 66+64 (one step late);
      //   132 = 66x2 (doubled the key)
      prompt: "3, 4, 6, 10, 18, 34, ?",
      options: ["66", "98", "102", "130", "132"],
      answer: 0,
    },
    {
      id: "nsr-013", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.2, b: 0.7, c: 0.2,
      // rule: alternating +1, x2
      // rebuilt 2026-08: the previous item (x3-2) was near-isomorphic to
      // nsr-006 (x3+2) via the geometric-differences route
      // distractors: 7 = repeated an early term; 15 = repeated the last
      //   term; 16 = 15+1 (applied +1 one step early); 60 = 30x2
      //   (continued x2)
      prompt: "2, 3, 6, 7, 14, 15, 30, ?",
      options: ["16", "60", "15", "7", "31"],
      answer: 4,
    },
    {
      id: "nsr-014", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.3, b: 1.3, c: 0.2,
      // rule: second differences 1,2,3,4
      // distractors: 43 = 31+12 (repeated the last difference);
      //   62 = 31x2 (doubled the last term); 71 = 48+23 (one step late);
      //   36 = 31+5 (reused an old difference)
      prompt: "1, 3, 6, 11, 19, 31, ?",
      options: ["43", "48", "62", "71", "36"],
      answer: 1,
    },
    {
      id: "nsr-015", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.4, b: 1.8, c: 0.2,
      // rule: a(n)=2a(n-1)+(n-1), with a(1)=1
      // distractors: 126 = 2x42+42 (added the last term instead of n-1);
      //   168 = 42x4 (wrong multiplier); 178 = 89x2 (doubled the key);
      //   184 = 2x89+6 (one step late)
      prompt: "1, 3, 8, 19, 42, ?",
      options: ["126", "168", "178", "89", "184"],
      answer: 3,
    },
    {
      id: "nsr-016", subtest: "numberSeries", broad: "Gq", narrow: "RQ",
      a: 1.4, b: 2.4, c: 0.2,
      // rule: a(n)=a(n-1)+2a(n-2) - true ceiling item (audit §2.4)
      // distractors: 27 = repeated the oldest shown term; 53 = repeated
      //   the last term; 79 = 2x53-27 (sign error on the older term);
      //   80 = 53+27 (plain sum)
      prompt: "2, 3, 7, 13, 27, 53, ?",
      options: ["107", "53", "79", "80", "27"],
      answer: 0,
    },
  ],
};

const QC_OPTIONS = [
  "Quantity A is greater",
  "Quantity B is greater",
  "The two quantities are equal",
  "Cannot be determined from the information given",
];

// ---------------------------------------------------------------------------
// Quantitative Comparison (qcp-001..020)
//
// b span -2.8 .. +1.6, a 0.9-1.4 (flattened, no lockstep ramp), c = 1/4
// (4 options). Re-anchored 2026-08 per docs/DIFFICULTY_AUDIT.md §2.5: the
// authored top third was over-placed by 0.5-2.5 logits (the factorial and
// permutation ceilings are knowledge checks, not reasoning ceilings).
// qcp-006 was re-keyed off qcp-004's a^b-vs-b^a twin structure (now a
// root-vs-integer comparison at the same tier, key re-verified: 50 > 49 so
// sqrt(50) > 7, no free variables). The instructions state that unbound
// variables range over all reals, which makes the two
// cannot-be-determined items (qcp-009, qcp-013) fair rather than
// trick-based. 2026-08-21 floor revision (audit §9): qcp-019/020 are
// single-operation basals below the old -2.2 floor. 2026-08-21
// D-distribution revision (red-team audit): D keys previously occurred
// only on the two bare-variable items, so a test-wise examinee could
// delete "Cannot be determined" a priori on every concrete-looking item.
// qcp-002 (was "4 x 9 vs 6 x 6", key equal) and qcp-010 (was
// square-vs-rectangle perimeters, key B) were re-authored as
// underdetermined comparisons keyed D; both hide their free degree of
// freedom (a product under a fixed sum; a rectangle under a fixed area),
// so "no visible variable => eliminate D" now fails on concrete-looking
// items. The answer histogram is A=5, B=5, C=6, D=4 - "always equal"
// lifts chance to only 6/20 (was 7/20); C stays modal by one item, which
// the histogram guard in test/gq-keys.test.ts bounds. Both re-keys are
// exact (see the item comments).
// ---------------------------------------------------------------------------

export const quantComparison: Subtest = {
  id: "quantComparison",
  name: "Quantitative Comparison",
  broad: "Gq",
  narrow: ["RQ"],
  instructions:
    "Compare the two quantities. Choose whether A is greater, B is greater, they are equal, or there is not enough information to decide. Unless a quantity is fixed by the statement, a variable may take any real value — positive, negative, or zero.",
  budgetMin: 19,
  routing: { maxItems: 15, minItems: 7, ceilingMisses: 4, targetSe: 0.50, entryTheta: 0 },
  // Unscored sample: one-step comparison, verified 6 vs 5.
  practice: [
    {
      id: "prac-qcp-01", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -3, c: 0.25,
      prompt: "Quantity A: 3 + 3\nQuantity B: 5",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "prac-qcp-02", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -3, c: 0.25,
      prompt: "Quantity A: 2 × 6\nQuantity B: 4 + 8",
      options: QC_OPTIONS,
      answer: 2,
    },
  ],
  items: [
    {
      id: "qcp-001", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -2.2, c: 0.25,
      // verified: 27 vs 26
      prompt: "Quantity A: 12 + 15\nQuantity B: 30 - 4",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-002", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1, b: -2, c: 0.25,
      // verified: the sum fixes no product - 5x5 = 25 > 24, 4x6 = 24 = 24,
      // 1x9 = 9 < 24, so the direction genuinely varies. Re-keyed 2026-08-21
      // (red-team audit): was "4 x 9 vs 6 x 6" (36 = 36, key equal);
      // converted to an underdetermined comparison with no visible variable
      // so "no variable => eliminate D" fails here.
      prompt: "Quantity A: The product of two numbers whose sum is 10\nQuantity B: 24",
      options: QC_OPTIONS,
      answer: 3,
    },
    {
      id: "qcp-003", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1, b: -1.5, c: 0.25,
      // verified: 0.5 vs 0.6
      prompt: "Quantity A: 1/2\nQuantity B: 3/5",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-004", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.1, b: -1.2, c: 0.25,
      // verified: 32 vs 25
      prompt: "Quantity A: 2^5\nQuantity B: 5^2",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-005", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1, b: -0.7, c: 0.25,
      // verified: 20 vs 20 (exact integer arithmetic: 25*80/100 both sides)
      prompt: "Quantity A: 25% of 80\nQuantity B: 80% of 25",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-006", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.2, b: -0.5, c: 0.25,
      // verified: sqrt(50) ≈ 7.071 > 7, since 50 > 49 and sqrt is monotone;
      // both quantities are constants - no edge cases. Re-keyed 2026-08 off
      // the former 3^5-vs-5^3 twin of qcp-004 (audit §2.5).
      prompt: "Quantity A: The square root of 50\nQuantity B: 7",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-007", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1, b: -0.1, c: 0.25,
      // verified: 30/3 = 10 vs 10
      prompt: "Quantity A: The average of 4, 8, and 18\nQuantity B: 10",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-008", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.1, b: 0.3, c: 0.25,
      // verified: 9 vs 9 (x is fixed at -3 by the statement)
      prompt: "Quantity A: x squared, where x = -3\nQuantity B: 9",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-009", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.3, b: 0.9, c: 0.25,
      // verified: x unconstrained: x=2 makes B greater, x=1/2 makes A greater
      prompt: "Quantity A: x squared\nQuantity B: x cubed",
      options: QC_OPTIONS,
      answer: 3,
    },
    {
      id: "qcp-010", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.1, b: 0.4, c: 0.25,
      // verified: the area fixes no perimeter - 4x9 gives 26 < 30, 3x12
      // gives 30 = 30, 2x18 gives 40 > 30 (and with real-valued sides the
      // perimeter 2(a + 36/a) takes every value from 24 up), so the
      // direction genuinely varies. Re-keyed 2026-08-21 (red-team audit):
      // was "perimeter of a square with area 36" vs "perimeter of a 4 by 9
      // rectangle" (24 < 26, key B); converted to an underdetermined
      // comparison with no visible variable.
      prompt: "Quantity A: The perimeter of a rectangle with area 36\nQuantity B: 30",
      options: QC_OPTIONS,
      answer: 3,
    },
    {
      id: "qcp-011", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.3, b: 1, c: 0.25,
      // verified: 1073741824 vs 3486784401
      prompt: "Quantity A: 2^30\nQuantity B: 3^20",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-012", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.2, b: 0.7, c: 0.25,
      // verified: n = 6 vs 6
      prompt: "Quantity A: n, where 3n + 7 = 25\nQuantity B: 6",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-013", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.4, b: 1.1, c: 0.25,
      // verified: y = 4 or y = -4
      prompt: "Quantity A: y, where y squared = 16\nQuantity B: 4",
      options: QC_OPTIONS,
      answer: 3,
    },
    {
      id: "qcp-014", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.2, b: 1.2, c: 0.25,
      // verified: 23, 29, 31, 37 = 4 vs 4
      prompt: "Quantity A: The number of primes between 20 and 40\nQuantity B: 4",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-015", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.3, b: 1.5, c: 0.25,
      // verified: 27/1000 vs 36/1000
      prompt: "Quantity A: 0.3 cubed\nQuantity B: 0.3 squared x 0.4",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-016", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.4, b: 1.6, c: 0.25,
      // verified: 41/42 vs 1, verified with exact rational arithmetic
      prompt: "Quantity A: 1/2 + 1/3 + 1/7\nQuantity B: 1",
      options: QC_OPTIONS,
      answer: 1,
    },
    {
      id: "qcp-017", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.2, b: 0.8, c: 0.25,
      // verified: 823543 vs 5040
      prompt: "Quantity A: 7^7\nQuantity B: 7 factorial",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-018", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 1.3, b: 1.2, c: 0.25,
      // verified: 5x4x3 = 60 vs 60
      prompt: "Quantity A: The number of distinct three-letter arrangements using letters from ABCDE with no repeats\nQuantity B: 60",
      options: QC_OPTIONS,
      answer: 2,
    },
    {
      id: "qcp-019", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -2.8, c: 0.25,
      // verified: 7 vs 6 (basal)
      prompt: "Quantity A: 3 + 4\nQuantity B: 2 x 3",
      options: QC_OPTIONS,
      answer: 0,
    },
    {
      id: "qcp-020", subtest: "quantComparison", broad: "Gq", narrow: "RQ",
      a: 0.9, b: -2.5, c: 0.25,
      // verified: 35 vs 75 (basal)
      prompt: "Quantity A: 100 - 65\nQuantity B: 100 - 25",
      options: QC_OPTIONS,
      answer: 1,
    },
  ],
};
